<a href="https://colab.research.google.com/github/AleOi2/Competitions/blob/master/PrimeiraCompeticao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conectando  CoLab com Kaggle

In [0]:
from google.colab import files
files.upload()
# Adicione arquivo kaggle.json utilizando o kaggle
# na aba my account

In [12]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!ls ~/.kaggle
!pip install -q kaggle
!pip install -q kaggle-cli
#!kaggle datasets list
#!kaggle competitions list
!kaggle competitions download -c ieee-fraud-detection
!mkdir /root/user

import os
import zipfile
import re
path = '/content/'
directory_to_extract_to = '/root/user/'
os.chdir('/content/')
os.listdir()

arquivos = [re.findall('.*\.zip', file) for file in os.listdir()]
for file in arquivos:
  if file != []:
    path_to_zip_file = path + file[0]
    with zipfile.ZipFile(path_to_zip_file, 'r') as zip_ref:
      zip_ref.extractall(directory_to_extract_to)

kaggle.json
train_transaction.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_identity.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
test_transaction.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
test_identity.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
sample_submission.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
mkdir: cannot create directory ‘/root/user’: File exists

# Análise de Dados

In [0]:
import pandas as pd

# Importando dados de submissao
sample_sub = pd.read_csv('~/user/sample_submission.csv')

# Importando dados de Treino
train_transaction = pd.read_csv('~/user/train_transaction.csv')
train_identity = pd.read_csv('~/user/train_identity.csv')

# Importando dados de Teste
test_transaction = pd.read_csv('~/user/test_transaction.csv')
test_identity = pd.read_csv('~/user/test_identity.csv')

In [14]:
train_transaction.head(3)

   TransactionID  isFraud  TransactionDT  ...  V337 V338  V339
0        2987000        0          86400  ...   NaN  NaN   NaN
1        2987001        0          86401  ...   NaN  NaN   NaN
2        2987002        0          86469  ...   NaN  NaN   NaN

[3 rows x 394 columns]

In [0]:
train = pd.merge(train_transaction, train_identity, on='TransactionID', how='left')
test = pd.merge(test_transaction, test_identity, on='TransactionID', how='left')

In [0]:
train.head()

   TransactionID  isFraud  ...  DeviceType                     DeviceInfo
0        2987000        0  ...         NaN                            NaN
1        2987001        0  ...         NaN                            NaN
2        2987002        0  ...         NaN                            NaN
3        2987003        0  ...         NaN                            NaN
4        2987004        0  ...      mobile  SAMSUNG SM-G892A Build/NRD90M

[5 rows x 434 columns]

In [0]:
train.describe()

       TransactionID        isFraud  ...        id_26         id_32
count   5.905400e+05  590540.000000  ...  5163.000000  77586.000000
mean    3.282270e+06       0.034990  ...   149.070308     26.508597
std     1.704744e+05       0.183755  ...    32.101995      3.737502
min     2.987000e+06       0.000000  ...   100.000000      0.000000
25%     3.134635e+06       0.000000  ...   119.000000     24.000000
50%     3.282270e+06       0.000000  ...   149.000000     24.000000
75%     3.429904e+06       0.000000  ...   169.000000     32.000000
max     3.577539e+06       1.000000  ...   216.000000     32.000000

[8 rows x 403 columns]

In [17]:
cat_cols = list(train.select_dtypes(include=['object']).columns)
cat_cols

['ProductCD',
 'card4',
 'card6',
 'P_emaildomain',
 'R_emaildomain',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'id_12',
 'id_15',
 'id_16',
 'id_23',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

In [29]:
# Verificando dados nulos 
data_null = train.isnull().sum()/len(train)
data_null = data_null.drop(data_null[data_null == 0].index).sort_values(ascending = False)
missing_data = pd.DataFrame({'Missing': data_null})
missing_data.head(3)
print(missing_data.shape)

(414, 1)

In [41]:
def FiltroNull(dados, fator):
  novos_dados = [index for index in dados.columns if dados[index].isnull().sum()/dados.shape[0] < (1-fator)]
  return novos_dados

def FiltroRepeat(dados, fator):
  novos_dados = [index for index in dados.columns if dados[index].value_counts(dropna=False, normalize=True).values[0] < (1-fator)]
  return novos_dados
# Deletando colunas com mais de 95% dados faltando
col_filtrado = FiltroNull(train, 0.95)
#col_filtrado = FiltroNull(train, 0.95)
#teste_filtrado = train[col_filtrado]
col_filtrado

['TransactionID',
 'isFraud',
 'TransactionDT',
 'TransactionAmt',
 'ProductCD',
 'card1',
 'card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'D1',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V279',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V320',
 'V321']